北京首都SOP 调整
VATPRChina/vatprc-docs pull request #7
Opened 2024-11-03 16:47 UTC by AaronZSAM101

1. 调整格式
2. 调整部分表达

2024-11-06 11:42 UTC, AaronZSAM101 commented
@xfoxfu 以后SOP的内容Assign给 @paul891014 ，谢谢。

2024-11-06 11:55 UTC, RudiZhang commented
> @xfoxfu 以后SOP的内容Assign给 @paul891014 ，谢谢。

@xfoxfu 可以先自动assign给 @paul891014 他那里审核通过后，由他assign给我进行审核，然后我这里直接merge

2024-12-08 12:49 UTC, xfoxfu requested changes

2024-12-08 12:49 UTC, xfoxfu commented on docs/aerodromes/ZBAA.md
> +管制员上线时需遵守 [VATSIM Code of Conduct (COC)](https://vatsim.net/docs/policy/code-of-conduct) ，并积极与上下级管制员协调以达成一致认知。
Foobar

2024-12-08 12:52 UTC, paul891014 requested changes

2024-12-08 12:53 UTC, xfoxfu approved these changes

2024-12-08 12:53 UTC, xfoxfu submitted a review, later dismissed

2025-01-21 01:51 UTC, LotinZhang approved these changes

2025-01-21 02:43 UTC, paul891014 approved these changes

2025-01-21 12:16 UTC, RudiZhang approved these changes

2025-01-21 12:16 UTC, merged